package gecko.ui.theme

import androidx.compose.ui.graphics.Color

internal val light_primary = Color(0xFF9c4045)
internal val light_onPrimary = Color(0xFFffffff)
internal val light_primaryContainer = Color(0xFFffd9da)
internal val light_onPrimaryContainer = Color(0xFF400008)
internal val light_secondary = Color(0xFF6e5d00)
internal val light_onSecondary = Color(0xFFffffff)
internal val light_secondaryContainer = Color(0xFFfce265)
internal val light_onSecondaryContainer = Color(0xFF221b00)
internal val light_tertiary = Color(0xFF1f5fa6)
internal val light_onTertiary = Color(0xFFffffff)
internal val light_tertiaryContainer = Color(0xFFd3e3ff)
internal val light_onTertiaryContainer = Color(0xFF001c3b)
internal val light_error = Color(0xFFB3261E)
internal val light_errorContainer = Color(0xFFF9DEDC)
internal val light_onError = Color(0xFFFFFFFF)
internal val light_onErrorContainer = Color(0xFF410E0B)
internal val light_background = Color(0xFFfdfcff)
internal val light_onBackground = Color(0xFF1b1b1b)
internal val light_surface = Color(0xFFfdfcff)
internal val light_onSurface = Color(0xFF1b1b1b)
internal val light_surfaceVariant = Color(0xFFE7E0EC)
internal val light_onSurfaceVariant = Color(0xFF49454F)
internal val light_outline = Color(0xFF79747E)
internal val light_inverseOnSurface = Color(0xFFf1f0f4)
internal val light_inverseSurface = Color(0xFF2f3033)
internal val light_inversePrimary = Color(0xFFffb2b4)
internal val light_shadow = Color(0xFF000000)

internal val dark_primary = Color(0xFFffb2b4)
internal val dark_onPrimary = Color(0xFF5f121b)
internal val dark_primaryContainer = Color(0xFF7d2a30)
internal val dark_onPrimaryContainer = Color(0xFFffd9da)
internal val dark_secondary = Color(0xFFdec64c)
internal val dark_onSecondary = Color(0xFF3a3000)
internal val dark_secondaryContainer = Color(0xFF534600)
internal val dark_onSecondaryContainer = Color(0xFFfce265)
internal val dark_tertiary = Color(0xFFa4c8ff)
internal val dark_onTertiary = Color(0xFF003060)
internal val dark_tertiaryContainer = Color(0xFF004789)
internal val dark_onTertiaryContainer = Color(0xFFd3e3ff)
internal val dark_error = Color(0xFFF2B8B5)
internal val dark_errorContainer = Color(0xFF8C1D18)
internal val dark_onError = Color(0xFF601410)
internal val dark_onErrorContainer = Color(0xFFF9DEDC)
internal val dark_background = Color(0xFF1b1b1b)
internal val dark_onBackground = Color(0xFFe2e2e6)
internal val dark_surface = Color(0xFF1b1b1b)
internal val dark_onSurface = Color(0xFFe2e2e6)
internal val dark_surfaceVariant = Color(0xFF49454F)
internal val dark_onSurfaceVariant = Color(0xFFCAC4D0)
internal val dark_outline = Color(0xFF938F99)
internal val dark_inverseOnSurface = Color(0xFF1b1b1b)
internal val dark_inverseSurface = Color(0xFFe2e2e6)
internal val dark_inversePrimary = Color(0xFF9c4045)
internal val dark_shadow = Color(0xFF000000)

internal val seed = Color(0xFF6750A4)
internal val error = Color(0xFFB3261E)