package gecko.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF9c4045)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFffd9da)
val light_onPrimaryContainer = Color(0xFF400008)
val light_secondary = Color(0xFF6e5d00)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFfce265)
val light_onSecondaryContainer = Color(0xFF221b00)
val light_tertiary = Color(0xFF1f5fa6)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFd3e3ff)
val light_onTertiaryContainer = Color(0xFF001c3b)
val light_error = Color(0xFFB3261E)
val light_errorContainer = Color(0xFFF9DEDC)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410E0B)
val light_background = Color(0xFFfdfcff)
val light_onBackground = Color(0xFF1b1b1b)
val light_surface = Color(0xFFfdfcff)
val light_onSurface = Color(0xFF1b1b1b)
val light_surfaceVariant = Color(0xFFE7E0EC)
val light_onSurfaceVariant = Color(0xFF49454F)
val light_outline = Color(0xFF79747E)
val light_inverseOnSurface = Color(0xFFf1f0f4)
val light_inverseSurface = Color(0xFF2f3033)
val light_inversePrimary = Color(0xFFffb2b4)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFFffb2b4)
val dark_onPrimary = Color(0xFF5f121b)
val dark_primaryContainer = Color(0xFF7d2a30)
val dark_onPrimaryContainer = Color(0xFFffd9da)
val dark_secondary = Color(0xFFdec64c)
val dark_onSecondary = Color(0xFF3a3000)
val dark_secondaryContainer = Color(0xFF534600)
val dark_onSecondaryContainer = Color(0xFFfce265)
val dark_tertiary = Color(0xFFa4c8ff)
val dark_onTertiary = Color(0xFF003060)
val dark_tertiaryContainer = Color(0xFF004789)
val dark_onTertiaryContainer = Color(0xFFd3e3ff)
val dark_error = Color(0xFFF2B8B5)
val dark_errorContainer = Color(0xFF8C1D18)
val dark_onError = Color(0xFF601410)
val dark_onErrorContainer = Color(0xFFF9DEDC)
val dark_background = Color(0xFF1b1b1b)
val dark_onBackground = Color(0xFFe2e2e6)
val dark_surface = Color(0xFF1b1b1b)
val dark_onSurface = Color(0xFFe2e2e6)
val dark_surfaceVariant = Color(0xFF49454F)
val dark_onSurfaceVariant = Color(0xFFCAC4D0)
val dark_outline = Color(0xFF938F99)
val dark_inverseOnSurface = Color(0xFF1b1b1b)
val dark_inverseSurface = Color(0xFFe2e2e6)
val dark_inversePrimary = Color(0xFF9c4045)
val dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)